const POST_ACTION_TYPES = {
    GET_POSTS_RERQUEST_START: "GET_POSTS_RERQUEST_START",
    GET_POSTS_RERQUEST_SUCCESS: "GET_POSTS_RERQUEST_SUCCESS",
    GET_POSTS_RERQUEST_FAILURE: "GET_POSTS_RERQUEST_FAILURE",

    ADD_POST_RERQUEST_START: "ADD_POST_RERQUEST_START",
    ADD_POST_RERQUEST_SUCCESS: "ADD_POST_RERQUEST_SUCCESS",
    ADD_POST_RERQUEST_FAILURE: "ADD_POST_RERQUEST_FAILURE",

    UPDATE_POST_RERQUEST_START: "UPDATE_POSTS_RERQUEST_START",
    UPDATE_POST_RERQUEST_SUCCESS: "UPDATE_POSTS_RERQUEST_SUCCESS",
    UPDATE_POST_RERQUEST_FAILURE: "UPDATE_POST_RERQUEST_FAILURE",

    DELETE_POSTS_RERQUEST_START: "DELETE_POSTS_RERQUEST_START",
    DELETE_POSTS_RERQUEST_SUCCESS: "DELETE_POSTS_RERQUEST_SUCCESS",
    DELETE_POSTS_RERQUEST_FAILURE: "DELETE_POSTS_RERQUEST_FAILURE"
}

export default POST_ACTION_TYPES;